
ADD_SUBDIRECTORY(third-party)
FIND_LIBRARY(TP_THIRD_PARTY_LIBRARY tpthirdparty third-party)
INCLUDE_DIRECTORIES(third-party)

IF(UNIX)
  INCLUDE(FindALSA.cmake)
  LINK_LIBRARIES(${ALSA_LIBRARY})
ENDIF(UNIX)
