FIND_PATH(PYTHONQT_INCLUDE_DIR PythonQt.h
"../PythonQt-1.0/src"
/usr/include
"/home/lexa/SRC/PythonQt-1.0/src"
)

IF(NOT PYTHONQT_INCLUDE_DIR)
MESSAGE(FATAL_ERROR "PythonQt not found")
ENDIF(NOT PYTHONQT_INCLUDE_DIR)

FIND_LIBRARY(PYTHONQT_LIBRARY PythonQt
"../PythonQt-1.0/lib"
/usr/lib
"/home/lexa/SRC/PythonQt-1.0/lib"
)

IF(NOT PYTHONQT_LIBRARY)
MESSAGE(FATAL_ERROR "PythonQt library not found")
ENDIF(NOT PYTHONQT_LIBRARY)

MACRO (lfUSE_PYTHONQT)
    INCLUDE_DIRECTORIES(${PYTHONQT_INCLUDE_DIR})
    LINK_LIBRARIES(${PYTHONQT_LIBRARY})
ENDMACRO (lfUSE_PYTHONQT)
